# Generated by Django 3.2 on 2021-04-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210422_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='Total_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price_of_one',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
